### ISSUE TITLE
Is there a key available for the column names in the .csv file?

### ISSUE THREAD

**Issue by JamesTimothyMeech** [naresh-shanbhag/UIUC-IMC-Benchmarking#2]
Thanks for compiling this great resource!

Reading the paper and looking at the .csv file I am finding it hard to come up with natural language descriptions of the shortened column titles in the .csv file. 

I found clues about what some but not all of the columns headings mean in the python plotting script.

Is there anywhere I can find a key that expands the shortened column titles or explains what they are to an outsider to the field such as myself?

**Comment by JamesTimothyMeech** [comment]
This is what I have so far: 
TOPS_mm2 = Compute Density (TOPS/mm2)
TOPS_W = Energy Efficiency (TOPS/W)
B_pre_ADC  = Pre-ADC Information Content (bits)
Tech  = Technology Node Size (nm)
Year  = Year of Publication
core_size  = Core Size(Kb)
N_row  = ? 
N_col  = ?
Vdd  = Supply Voltage (V)
B_X  = ?
B_W  = ?
B_ADC = Analog to Digital Converter Precision (bits)
R_C  = ?
R  = ?
C_C  = ?
C  = ?
N_ADC  = ?Number of Analog to Digital Converters in Implementation?
N  = ?
N_1b  = ?
B_core = ?
alpha = ?
B_col  = ?
T_core_ns  = ?
E_OP1_fJ = ?
N_core = ?
E_col_fJ  = ?
E_core_pJ  = ?
E_mvm_pJ  = ?
Cell_Type = ?
Compute_Mod = Compute Model
Arch = Architecture (SRAM, eNVM, DRAM, eDRAM, or Digital )
TOPS_a = ?
TOPS = Throughput (TOPS)
IMC_Proc = ?

**Comment by JamesTimothyMeech** [comment]
I am particularly interested in knowing what T_core_ns, N_ADC, CR, E_OP1, E_col, E_core, E_mvm, IMC_Processor, and TOPS_a  are!

**Comment by soonhahwang** [comment]
Hi James,

Thank you for asking. This has just caught my attention, as we have migrated our repo to https://github.com/UIUC-IMC/UIUC-IMC-Benchmarking.

The following is what you are looking for:

**N_row** = Number of rows per bank
**N_col** = Number of columns per bank
**B_X** = Input Precision in IMC Bank
**B_W** = Weight Precision in IMC Bank
**R_C** = Number of physical rows computed / read cycle
**R** = Number of physical rows in ADC column
**C_C** = Number of physical columns computed / read cycle
**C** = Number of physical columns per ADC
**N**_ADC = Number of ADCs in parallel
**N** = Dot product dimension
**N_1b** = Number of 1 bit operation per invocation
**B_core** = Number of MAC operations in a bank
**alpha** =  Number of array invocations for 1 MVM (total input precision / input precision in IMC bank)
**T_core_ns** = Latency/Delay of 1 invocation
**E_OP1_fJ** = Energy per 1 bit Operation
**N_core** = Number of IMC core in the architecture
**E_col_fJ** = Energy per ADC column in fJ
**E_core_pJ** = Energy per IMC core in 1 invocation in pJ
**E_mvm_pJ** = Total energy per multi-bit MVM
**Cell_Type** = Type of a bitcell used in memory
**TOPS_a** = Architecture throughput
**IMC_Proc** = Y if the design is IMC Processor, otherwise blank
